### PR TITLE
fix: Use libusb_set_option, set_debug is deprecated

### PR DESCRIPTION
**Pull request by captn3m0**

### CODE REVIEW

**Comment by captn3m0** [comment]
@krayon Can this be merged?

**Comment by krayon** [comment]
Merged in commit 89ef052be18c07ec651f23fdc5888cdd7a69da04

**Comment by krayon** [comment]
Merged into master @ 5c8a2b8b4b961c8d7f9f1bdec64a840e64e86dd5

**Comment by captn3m0** [comment]
It works :+1: 

Thanks for the release!

**Pull request closed without merging**
